### ISSUE TITLE
VOC dataset

### ISSUE THREAD

**Issue by Kevin9737** [milkxie/PML-CDCR#1]
Hi,
Thanks for your excellent work. I can not manage to find the VOC dataloader. Could you please upload the corresponding code?
Thans a lot!

**Comment by xiemk** [comment]
Sorry for late response! 
Please see: https://github.com/milkxie/SPML-LAC/blob/master/lib/dataset/handlers.py
Hope this link can solve your problem!
If there is any problem, please contact with me via github or email.
